# Generated by Django 4.2 on 2023-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
